# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20151216_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0422\u0438\u043f \u0434\u0430\u043d\u043d\u044b\u0445',
                'verbose_name_plural': '\u0422\u0438\u043f\u044b \u0434\u0430\u043d\u043d\u044b\u0445',
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0422\u0438\u043f \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u0430',
                'verbose_name_plural': '\u0422\u0438\u043f\u044b \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u0430',
            },
        ),
        migrations.CreateModel(
            name='FuncType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0422\u0438\u043f \u0444\u0443\u043d\u043a\u0446\u0438\u0438',
                'verbose_name_plural': '\u0422\u0438\u043f\u044b \u0444\u0443\u043d\u043a\u0446\u0438\u0438',
            },
        ),
        migrations.AddField(
            model_name='wpparam',
            name='async',
            field=models.CharField(default=b'', max_length=200, verbose_name='\u0424\u043b\u0430\u0433 \u0430\u0441\u0438\u043d\u0445\u0440\u043e\u043d\u043d\u043e\u0441\u0442\u0438'),
        ),
        migrations.AddField(
            model_name='wpparam',
            name='device_address',
            field=models.CharField(default=b'', max_length=200, verbose_name='\u0410\u0434\u0440\u0435\u0441\u0441 \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u0430'),
        ),
        migrations.AddField(
            model_name='wpparam',
            name='source',
            field=models.CharField(default=b'', max_length=200, verbose_name='\u0418\u0441\u0442\u043e\u0447\u043d\u0438\u043a'),
        ),
        migrations.AddField(
            model_name='wpparam',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.DeviceType', verbose_name='\u0422\u0438\u043f \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u0430'),
        ),
        migrations.AddField(
            model_name='wpparam',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.DataType', verbose_name='\u0422\u0438\u043f \u0434\u0430\u043d\u043d\u044b\u0445'),
        ),
        migrations.AddField(
            model_name='wpparam',
            name='type_func',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.FuncType', verbose_name='\u0422\u0438\u043f \u0444\u0443\u043d\u043a\u0446\u0438\u0438'),
        ),
    ]
