# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 09:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20151225_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standtask_state',
            old_name='standtask_id',
            new_name='standtask',
        ),
        migrations.RenameField(
            model_name='standtask_state',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='training_log',
            old_name='user_id',
            new_name='user',
        ),
    ]
