# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20151226_0902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training_state',
            old_name='user_id',
            new_name='user',
        ),
    ]
