# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20151226_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wpparam',
            name='async',
            field=models.CharField(blank=True, default=b'', max_length=200, null=True, verbose_name='\u0424\u043b\u0430\u0433 \u0430\u0441\u0438\u043d\u0445\u0440\u043e\u043d\u043d\u043e\u0441\u0442\u0438'),
        ),
    ]
