# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20160104_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wpparam',
            name='async',
            field=models.CharField(blank=True, default=b'', max_length=500, null=True, verbose_name='\u0424\u043b\u0430\u0433 \u0430\u0441\u0438\u043d\u0445\u0440\u043e\u043d\u043d\u043e\u0441\u0442\u0438'),
        ),
        migrations.AlterField(
            model_name='wpparam',
            name='device_address',
            field=models.CharField(blank=True, default=b'', max_length=500, null=True, verbose_name='\u0410\u0434\u0440\u0435\u0441\u0441 \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u0430'),
        ),
        migrations.AlterField(
            model_name='wpparam',
            name='source',
            field=models.CharField(blank=True, default=b'', max_length=500, null=True, verbose_name='\u0418\u0441\u0442\u043e\u0447\u043d\u0438\u043a'),
        ),
    ]
